import { Cube, Cubes } from './cubes';

export default class OakTree
{
	public static crown_base   = 5;
	public static crown_height = 4

	public static crown: Cube[][][] =
	[
		[
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_wood,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
		],

		[
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
			[
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
			],
		],

		[
			[
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
			],
		],

		[
			[
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.oak_leaves,
				Cubes.air,
			],
			[
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
				Cubes.air,
			],
		],
	];
}
