import { Block, Blocks } from './blocks';

export default class OakTree
{
	public static crown_base   = 5;
	public static crown_height = 4

	public static crown: Block[][][] =
	[
		[
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_wood,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
		],

		[
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
			[
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
			],
		],

		[
			[
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
			],
		],

		[
			[
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.oak_leaves,
				Blocks.air,
			],
			[
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
				Blocks.air,
			],
		],
	];
}
